/**
 * Slug generator for community posts. Mirrors the `posts_generate_slug`
 * Postgres function (migration 20260601000001) so app and DB stay in sync.
 *
 * URL pattern: /community/{short_id}/{slug?}
 *  - short_id is the lookup key (generated by DB default — 8 hex chars from
 *    gen_random_uuid). We never derive it in the app.
 *  - slug is decorative for SEO and UX; route layer canonical-corrects
 *    mismatches.
 */

const SLUG_MAX_LENGTH = 120;
const SLUG_FALLBACK = 'post';

/**
 * Generate a URL-safe slug from a post title.
 *
 * - Preserves Hangul (Korean URLs index fine in Google as percent-encoded).
 * - Strips emoji and most special characters.
 * - Falls back to 'post' for all-emoji / empty titles.
 * - Stable: same input always produces same output (no randomness here —
 *   uniqueness comes from short_id, not slug).
 */
export function generateSlug(title: string): string {
  let s = (title ?? '')
    // 1) keep latin alnum, hangul, whitespace, hyphen — strip everything else
    .replace(/[^a-zA-Z0-9가-힣ㄱ-ㅎㅏ-ㅣ\s\-]/g, '')
    // 2) collapse whitespace runs to single hyphen
    .replace(/\s+/g, '-')
    // 3) collapse consecutive hyphens
    .replace(/-+/g, '-')
    // 4) trim hyphens
    .replace(/^-+|-+$/g, '')
    // 5) lowercase (no-op for hangul; normalizes latin chars)
    .toLowerCase();

  if (!s) s = SLUG_FALLBACK;

  return s.slice(0, SLUG_MAX_LENGTH);
}
